name: Backend Production Deployment
on:
    push:
        branches:
            - main
        paths:
            - backend/**
jobs:
    deploy-be-production:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  port: 22
                  script: |
                      cd chatbot/backend/
                      docker compose down
                      git pull origin main
                      docker compose up --build --detach chatbot_api
